language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - '7.3'

matrix:
    fast_finish: true

before_install:
    - composer self-update
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install: composer update --prefer-dist

script: vendor/bin/phpunit --coverage-clover=coverage.clover
